package:
  name: newick_utils
  version: 1.6.0

source:
    url: http://cegg.unige.ch/pub/newick-utils-1.6.tar.gz
    fn: newick-utils-1.6.tar.gz

build:
  number: 0

#requirements:
#  build:
#    - gcc   # [linux]
#    - llvm  # [osx]

test:
  commands:
    - nw_prune -h

about:
  home: http://cegg.unige.ch/newick_utils
  license: BSD
  summary: The Newick Utilities are a suite of Unix shell tools for processing phylogenetic trees. We distribute the package under the BSD License. Functions include re-rooting, extracting subtrees, trimming, pruning, condensing, drawing (ASCII graphics or SVG).

